### ISSUE TITLE
Usernames

### ISSUE THREAD

**Issue by levidurfee** [wappr/ticklr#6]
Should usernames be their email address, since those would be unique for each person. We wouldn't have to worry about conflicts.

Only possible issue I could foresee, a user needing two accounts for some reason.

Example@example.com might work at company 1 and they are on the board of company 2. I guess we would just make that one user (email address) be part of both organizations.

Conclusion: I think usernames should be their email.

**Comment by levidurfee** [comment]
If @teefort agrees, I will make this change.

**Comment by teefort** [comment]
I think this is a good idea. It's easier for people to remember their email than a username anyway.

**Comment by levidurfee** [comment]
5fe578ba313d6ad743a65f6a499e6e3c787f12ce closes this.
